apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-run
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: git-url
      value: https://github.com/swathinaikm667-hue/juphc-tc_pipeline.git
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: tekton-source-pvc
